# Site
repository: ravi-vadlamani/ravi-vadlamani.github.io
favicon: images/favicon.ico

# Personal info
name: Ravi Vadlamani
title: Undergrad Research Assistant in Ecotoxiclogy Labs at Ryerson University
email: rvadlamani@ryerson.ca
website: ravi-vadlamani.github.io

# Social links
# twitter_username: facespics
github_username:  ravi-vadlamani
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: ravi-vadlamani
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Undergraduate biology student with an experience in industry looking for research opportunities to
  expand horizons and find a niche. Exceptional laboratory performance combined with a statistical analysis skill set is ideal for a professional results oriented workflow. 


  I am most skilled in: <mark>Spectrophotometry</mark> <mark>Gel Electrophoresis</mark> <mark>PCR</mark> and <mark>Gas Chromatography</mark>


  Fields of interest: 
  -  Application of Microbiology
  -  Viruses and Vaccines
  -  Environmental Biology and Sustainability

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Science is my passion and it extends to everything I do, my treasured interests include:
   - Archery
   - Astronomy and Star Gazing
   - Books
#   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
