# Site
repository: ravi-vadlamani/ravi-vadlamani.github.io
favicon: images/favicon.ico

# Personal info
name: Ravi Vadlamani
title: Undergrad Research Assistant in Ecotoxiclogy Labs at Ryerson University
email: rvadlamani@ryerson.ca
website: ravi-vadlamani.github.io

# Social links
# twitter_username: facespics
github_username:  ravi-vadlamani
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: absolute_rave
linkedin_username: ravi-vadlamani
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

google_analytics: "G-V9GY08EE6E"

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Hey there! Thanks for stopping by.
  
  My name is **Ravi**{: style="color: #3385D9;"}, _an undergraduate biology student_ who is passionate about microbiology and its applications to make the world a better place. I'm currently interested in research opportunities to expand horizons and find a niche.
  
  My exceptional laboratory performance combined with a statistical analysis skill set are ideal for a company where a result oriented workflow is desirable. With experience in research & development as well as application in the industry, my workflow is quite adaptable and in-fact I enjoy a challenge that requires both technical and hands-on approach to find a solution.
  <br/><br/>
  Things I'm good at:
  -  Lab & Field skills: <mark>UV/Vis Spectrophotometry</mark> <mark>PCR & Gel Electrophoresis</mark> <mark>Gas Chromatography (GC)</mark>  <mark>Cell Cultures</mark> <mark>Ecological Sampling</mark> <mark>Biomonitoring aquatic and terrestrial habitats</mark>
  -  Programming: <mark>C</mark> <mark>C++</mark> <mark>Python</mark>
  
  Things I'm learning:
  - <mark>Statistical analysis in R</mark> <mark>LaTeX</mark> <mark>MATLAB modelling</mark>
  <br/><br/>
  
  Fields of interest: 
  -  Application of Microbiology
  -  Viruses and Vaccines
  -  Environmental Biology and Sustainability
  -  Xenobiology

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Science is my passion and it extends to everything I do, my treasured interests include:
   - Astronomy and Star Gazing
   - Archery
   - Sci-Fi Novels
   - Philosophy
#   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
# remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
